Capitalize swift storage server middleware name
Trying to add a middleware to the server pipeline with
the following code:

     swift::storage::filter::recon { 'object': }
     class { 'swift::storage::all':
       object_pipeline => ['recon', 'object-server'],
     }

Triggers the following error:

     Error: Could not retrieve catalog from remote server: Error 400 on
     SERVER: Invalid relationship: Concat::Fragment[swift-object-6000] {
     before => Swift::Storage::Filter::recon[object] }, because
     Swift::Storage::Filter::recon[object] doesn't seem to be in the
     log
     Warning: Not using cache on failed catalog
     Error: Could not retrieve catalog; skipping run

Caplitalizing the middleware name worked for me.